"use client";

import { Button } from "../ui/button";
import { Download } from "lucide-react";

export function DownloadButtonSummary({
  title,
  summaryText,
  file_name,
  createdAt,
}: {
  title?: string;
  summaryText?: string;
  file_name: string;
  createdAt?: string;
}) {
  const handleDownload = () => {
    const summaryContent = `# ${title}
        Generated Summary for: ${file_name}
        \n\n${summaryText}
        Original file: ${file_name}
            Generated by AI Summarizer on ${
              createdAt || new Date().toLocaleDateString()
            }
        `;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title?.replace(/[^a-z0-9]/gi, " ")}.txt`;
    document.body.appendChild(link); // Append link to the body
    link.click();
    document.body.removeChild(link);
    // Clean up the URL object after download

    URL.revokeObjectURL(url);
  };

  return (
    <Button
      onClick={handleDownload}
      className="text-white font-bold cursor-pointer hover:no-underline cursor pointer flex items-center gap-2"
    >
      <Download className="h-5 w-5 text-white" />
      Download Summary
    </Button>
  );
}
